services:
  db:
    container_name: lootopia-db
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./docker.prod/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  fix-permissions-rustfs:
    image: alpine
    container_name: fix-permissions-rustfs
    command: >
      sh -c "
        chown -R 10001:10001 /data &&
        chown -R 10001:10001 /logs &&
        chown -R 10001:10001 /conf
      "
    volumes:
      - ./docker.prod/rustfs/data:/data
      - ./docker.prod/rustfs/logs:/logs
      - ./docker.prod/rustfs/conf:/conf
    restart: "no"

  bucket:
    image: rustfs/rustfs:latest
    container_name: lootopia-bucket
    restart: unless-stopped
    user: "10001:10001"
    depends_on:
      fix-permissions-rustfs:
        condition: service_completed_successfully
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=${S3_USER}
      - RUSTFS_SECRET_KEY=${S3_PASSWORD}
    volumes:
      - ./docker.prod/rustfs/data:/data
      - ./docker.prod/rustfs/logs:/logs
      - ./docker.prod/rustfs/conf:/etc/rustfs
    networks:
      - app-network

  nginx:
    container_name: lootopia-proxy
    build:
      context: ./nginx
    ports:
      - "80:80"
    environment:
      - DASHBOARD_DOMAIN=${DASHBOARD_DOMAIN}
      - MOBILE_DOMAIN=${MOBILE_DOMAIN}
    depends_on:
      - dashboard
      - mobile
      - api
    networks:
      - app-network

  dashboard:
    container_name: lootopia-dashboard
    build:
      context: .
      dockerfile: packages/dashboard/Dockerfile
    networks:
      - app-network

  mobile:
    container_name: lootopia-mobile
    build:
      context: .
      dockerfile: packages/mobile/Dockerfile
    networks:
      - app-network

  api:
    container_name: lootopia-api
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
      - bucket
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
