packages:
  - packages/*

allowBuilds:
  "@prisma/engines": false
  esbuild: true
  msw: false
  prisma: false
  oxlint: true
  oxlint-tsgolint: true

onlyBuiltDependencies:
  - esbuild

minimumReleaseAge: 1440
blockExoticSubdeps: true
